export const PLAYGROUND_ENTER_MS = 3_000;
export const PLAYGROUND_ENTER_TRAVEL_SPEED = 900;
export const PLAYGROUND_ARRIVAL_START_MS = 2_000;
export const PLAYGROUND_ARRIVAL_END_MS = 2_400;

export const PLAYGROUND_LEAVE_MS = 1_500;
export const PLAYGROUND_DEPARTURE_START_MS = 380;
export const PLAYGROUND_DEPARTURE_END_MS = 680;
export const PLAYGROUND_MUSEUM_RETURN_START_MS = 800;
