// Reviewed exhibit names, shared by the offline authoring and coverage checks.
export const chapterTitles = {
  intro: 'Introduction', habitats: 'Space habitats', infrastructure: 'Space infrastructure',
  planetary: 'Planetary engineering', energy: 'Stellar energy', propulsion: 'Interstellar travel',
  stellar: 'Stellar engineering', civilizations: 'Cosmic civilizations', search: 'Alien intelligence',
};
export const conceptTitles = {
  astroingenieria: 'Astroengineering', iss: 'Present-day space stations',
  'artificial-gravity': 'Artificial gravity through rotation', 'life-support': 'Closed ecosystems and life support',
  'bernal-sphere': 'Bernal sphere', 'stanford-torus': 'Stanford torus', 'oneill-cylinder': "O'Neill cylinder",
  'bishop-ring': 'Bishop ring', 'mckendree-cylinder': 'McKendree cylinder', 'asteroid-habitat': 'Habitats inside asteroids',
  ringworld: 'Megastructures in science fiction', 'reusable-launch': 'Reusable launch systems',
  'orbital-ports': 'Orbital spaceports', 'fuel-depots': 'Orbital propellant depots', 'lunar-bases': 'Lunar bases',
  isru: 'In-situ resource utilization (ISRU)', 'asteroid-mining': 'Asteroid mining', shipyards: 'Space shipyards',
  'space-elevator': 'Space elevator', tethers: 'Space tethers', skyhook: 'Skyhook', 'orbital-ring': 'Orbital ring',
  'launch-loop': 'Launch loop', 'mass-driver': 'Electromagnetic mass driver', 'space-law': 'Space law, economics and policy',
  exoplanets: 'Exoplanets', astrobiology: 'Astrobiology', 'habitable-zone': 'Habitable zone', habitability: 'Planetary habitability',
  paraterraforming: 'Paraterraforming', 'domed-cities': 'Domes and enclosed cities', worldhouse: 'Planetary enclosure (worldhouse)',
  terraforming: 'Terraforming', 'mars-terraforming': 'Terraforming Mars', 'venus-terraforming': 'Terraforming Venus',
  'floating-venus': 'Floating cities on Venus', 'orbital-mirrors': 'Orbital mirrors', sunshades: 'Space sunshades',
  'volatile-import': 'Importing volatiles', magnetosphere: 'Artificial magnetospheres', ecopoiesis: 'Ecopoiesis',
  'planetary-protection': 'Planetary protection', 'space-based-solar': 'Space-based solar power',
  'microwave-power': 'Microwave and laser power transmission', radiators: 'Waste heat and radiators',
  'dyson-swarm': 'Dyson swarm', 'dyson-ring': 'Dyson ring and network',
  'dyson-bubble': 'Dyson bubble and suspended satellites (statites)', 'dyson-shell': 'Rigid Dyson shell',
  'chemical-rockets': 'Chemical rockets', 'ion-engines': 'Ion engines', 'hall-thruster': 'Hall thrusters',
  'solar-electric': 'Solar electric propulsion', 'nuclear-electric': 'Nuclear electric propulsion',
  'nuclear-thermal': 'Nuclear thermal propulsion', 'project-orion': 'Project Orion', 'fusion-propulsion': 'Fusion propulsion',
  antimatter: 'Antimatter propulsion', 'bussard-ramjet': 'Bussard ramjet', 'solar-sail': 'Solar sails', 'laser-sail': 'Laser sails',
  'beamed-propulsion': 'Beamed propulsion', 'magnetic-sail': 'Magnetic sails', 'electric-sail': 'Electric sails',
  'relativistic-propulsion': 'Relativistic propulsion', 'interstellar-braking': 'Interstellar braking',
  worldship: 'Generation ships', alcubierre: 'Alcubierre propulsion', wormholes: 'Wormholes', reactionless: 'Reactionless drives',
  'stellar-physics': 'Stars as physical systems', 'stellar-engines': 'Stellar engines', shkadov: 'Shkadov thruster',
  caplan: 'Caplan engine', 'stellar-navigation': 'Stellar navigation', 'star-lifting': 'Extracting stellar matter (star lifting)',
  'plasma-processing': 'Stellar plasma processing', 'stellar-husbandry': 'Managing stellar evolution',
  'black-hole-engineering': 'Black hole engineering', kardashev: 'Kardashev scale',
  'tipo-i': 'Type I civilization', 'tipo-ii': 'Type II civilization', 'tipo-iii': 'Type III civilization',
  computronium: 'Computronium', 'jupiter-brain': 'Jupiter brain', 'matrioshka-brain': 'Matrioshka brain',
  'civilizaciones-digitales': 'Digital civilizations', postbiological: 'Postbiological civilizations',
  'von-neumann': 'Von Neumann probes', 'colonizacion-galactica': 'Galactic colonization',
  'civilizaciones-y-luz': 'Civilizations and the speed of light', 'deep-time': 'Deep time',
  'future-universe': 'The far future of the universe', 'cosmic-ethics': 'Cosmic ethics',
  seti: 'SETI', technosignatures: 'Technosignatures', 'radio-seti': 'Radio SETI', 'optical-seti': 'Optical SETI',
  'stellar-technosignatures': 'Technosignatures of stellar engineering', fermi: 'Fermi paradox',
  'great-filter': 'Great Filter', 'zoo-hypothesis': 'Zoo hypothesis', 'dark-forest': 'Dark forest hypothesis',
  'grabby-aliens': 'Expanding civilizations (grabby aliens)', 'civilizaciones-silenciosas': 'Silent civilizations',
  berserker: 'Destructive probes (berserkers)',
};
